package com.nathan.workspace.ui.theme

import androidx.compose.ui.graphics.Color

// ===== DESIGN.md M3 Dark Scheme (primary scheme) =====
val DarkPrimary = Color(0xFFA6C8FF)
val DarkOnPrimary = Color(0xFF02315E)
val DarkPrimaryContainer = Color(0xFF234776)
val DarkOnPrimaryContainer = Color(0xFFD5E3FF)
val DarkSecondary = Color(0xFFBDC7DC)
val DarkOnSecondary = Color(0xFF273141)
val DarkSecondaryContainer = Color(0xFF3D4758)
val DarkOnSecondaryContainer = Color(0xFFD9E3F8)
val DarkTertiary = Color(0xFFDABDE2)
val DarkOnTertiary = Color(0xFF3D2846)
val DarkTertiaryContainer = Color(0xFF553F5D)
val DarkOnTertiaryContainer = Color(0xFFF7D8FF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF111318)
val DarkOnBackground = Color(0xFFE1E2E9)
val DarkSurface = Color(0xFF111318)
val DarkOnSurface = Color(0xFFE1E2E9)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC4C6CF)
val DarkOutline = Color(0xFF8D9199)
val DarkOutlineVariant = Color(0xFF43474E)
val DarkSurfaceContainerLowest = Color(0xFF0C0E13)
val DarkSurfaceContainerLow = Color(0xFF191C20)
val DarkSurfaceContainer = Color(0xFF1D2024)
val DarkSurfaceContainerHigh = Color(0xFF282A2F)
val DarkSurfaceContainerHighest = Color(0xFF32353A)
val DarkInverseSurface = Color(0xFFE1E2E9)
val DarkInverseOnSurface = Color(0xFF2E3035)
val DarkInversePrimary = Color(0xFF3D5F90)

// ===== DESIGN.md M3 Light Scheme (opposite scheme) =====
val LightPrimary = Color(0xFF3D5F90)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD5E3FF)
val LightOnPrimaryContainer = Color(0xFF234776)
val LightSecondary = Color(0xFF555F71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD9E3F8)
val LightOnSecondaryContainer = Color(0xFF3D4758)
val LightTertiary = Color(0xFF6E5676)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF7D8FF)
val LightOnTertiaryContainer = Color(0xFF553F5D)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
val LightBackground = Color(0xFFF9F9FF)
val LightOnBackground = Color(0xFF191C20)
val LightSurface = Color(0xFFF9F9FF)
val LightOnSurface = Color(0xFF191C20)
val LightSurfaceVariant = Color(0xFFE0E2EC)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF74777F)
val LightOutlineVariant = Color(0xFFC4C6CF)

// ===== Status chip colors (consistent across schemes) =====
val ChipQueued = Color(0xFFA6C8FF)
val ChipRunning = Color(0xFF70D6B0)
val ChipSuccess = Color(0xFF52C77A)
val ChipCancelled = Color(0xFFF5C542)
val ChipFailure = Color(0xFFFF8A80)